export * from './debut/debut.component';
export * from './family/family.component';
export * from './jutsu/jutsu.component';
export * from './nature-type/nature-type.component';
export * from './personal/personal.component';
export * from './rank/rank.component';
export * from './tools/tools.component';
export * from './unique-traits/unique-traits.component';
export * from './voice-actors/voice-actors.component';
